FROM node:6-alpine
MAINTAINER "anujtech46" "anujtech46@gmail.com"
RUN apk update \
   && apk add zip \
   && mkdir -p /opt/botpress
RUN apk add python make g++
ADD src /opt/botpress/
WORKDIR /opt/botpress/
RUN npm install --unsafe-perm
WORKDIR /opt
CMD ["zip", "-r", "botpress_service.zip", "botpress"]